# Generated by Django 4.2 on 2023-05-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_image_imageup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageup',
            name='img',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
